version: '3.8'

volumes:
  data:

networks:
  default:
    name: main-network

services:
  nginx:
    build:
      context: ./.docker/nginx
    container_name: nginx
    networks:
      default:
        aliases:
          - ${DOMAIN}
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      DOMAIN: ${DOMAIN}
  php:
    build:
      context: ./.docker/php
    container_name: php
    volumes:
      - ./:/var/www/html:cached
      - ~/.ssh:/home/dockeruser/.ssh:rw
      - ./:/srv/app:rw