version: '3.8'

services:
#  database:
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-main}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-main}
#      POSTGRES_USER: ${POSTGRES_USER:-main}
#    ports:
#      - "5432:5432"

  # nginx
  nginx:
    ports:
      - "80"

  # php
  php:
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
      PHP_IDE_CONFIG: serverName=localhost
    ports:
      - "9000"
