version: '3.8'

volumes:
  db-data:

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_DB: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  app:
    build:
      context: ./.docker
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_SECRET=${APP_SECRET:-ChangeMe}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-ChangeMe}@database:5432/${POSTGRES_DB:-symfony}
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html:cached
      - ~/.ssh:/home/dockeruser/.ssh:rw
      - ./:/srv/app:rw
