version: '3.8'

volumes:
  db-data:

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_DB: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/html:delegated

  apache:
    image: httpd:latest
    depends_on:
      - php
      - database
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./.docker/apache/apache.conf:/etc/apache2/sites-available/000-default.conf
